"""adiciona medico, especialidade e tabela associativa

Revision ID: 38e215ab97d3
Revises: c283745678c4
Create Date: 2026-08-11 17:21:52.573858
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "38e215ab97d3"
down_revision: str | None = "c283745678c4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "especialidades",
        sa.Column("nome", sa.String(length=255), nullable=False, unique=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "medicos",
        sa.Column("nome", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "medico_especialidade",
        sa.Column("medico_id", sa.Uuid(), nullable=False),
        sa.Column("especialidade_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["especialidade_id"], ["especialidades.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["medico_id"], ["medicos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("medico_id", "especialidade_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("medico_especialidade")
    op.drop_table("medicos")
    op.drop_table("especialidades")
    # ### end Alembic commands ###
