"""adiciona clientes

Revision ID: c283745678c4
Revises:
Create Date: 2026-08-10 17:20:53.470987
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "c283745678c4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clientes",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("nome", sa.String(length=255), nullable=False),
        sa.Column("telefone", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("data_nascimento", sa.Date(), nullable=False),
        sa.CheckConstraint(
            "data_nascimento <= CURRENT_DATE",
            name="ck_cliente_data_nascimento_nao_futura",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
    op.create_index(
        "ix_clientes_nome_data_nascimento",
        "clientes",
        ["nome", "data_nascimento"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        "ix_clientes_nome_data_nascimento",
        table_name="clientes",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("clientes")
    # ### end Alembic commands ###
